import type { AbsenceType } from '../lib/types';

export const DEFAULT_ABSENCE_TYPE_ID = 'vacation';

// Catálogo inicial de demo: no fija duraciones legales; cada empresa debe adaptarlo a convenio y política interna.
export const ABSENCE_TYPES: readonly AbsenceType[] = [
	{
		id: 'vacation',
		name: 'Vacaciones',
		description: 'Ausencia por vacaciones anuales.',
		category: 'vacation',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: true,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'none',
		allowsPastRequests: false,
		minimumNoticeDays: null,
		calendarToken: 'vacation',
		active: true,
		sortOrder: 10,
	},
	{
		id: 'paid-moving',
		name: 'Mudanza',
		description: 'Permiso retribuido por cambio de domicilio.',
		category: 'paid_leave',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'paid-leave',
		active: true,
		sortOrder: 20,
	},
	{
		id: 'paid-family-hospitalization',
		name: 'Hospitalización o enfermedad grave de familiar',
		description: 'Permiso retribuido por hospitalización o enfermedad grave de familiar.',
		category: 'paid_leave',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'family-emergency',
		active: true,
		sortOrder: 30,
	},
	{
		id: 'paid-family-death',
		name: 'Fallecimiento de familiar',
		description: 'Permiso retribuido por fallecimiento de familiar.',
		category: 'paid_leave',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'family-emergency',
		active: true,
		sortOrder: 40,
	},
	{
		id: 'paid-public-duty',
		name: 'Deber público inexcusable',
		description: 'Permiso retribuido por deber público inexcusable.',
		category: 'paid_leave',
		unit: 'hours',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'paid-leave',
		active: true,
		sortOrder: 50,
	},
	{
		id: 'paid-family-force-majeure',
		name: 'Fuerza mayor familiar',
		description: 'Permiso retribuido por fuerza mayor familiar.',
		category: 'paid_leave',
		unit: 'hours',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'family-emergency',
		active: true,
		sortOrder: 60,
	},
	{
		id: 'medical-appointment',
		name: 'Consulta médica',
		description: 'Ausencia por consulta médica.',
		category: 'other',
		unit: 'hours',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'optional',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'medical',
		active: true,
		sortOrder: 70,
	},
	{
		id: 'personal-days',
		name: 'Asuntos propios',
		description: 'Ausencia por asuntos propios.',
		category: 'other',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'none',
		allowsPastRequests: false,
		minimumNoticeDays: null,
		calendarToken: 'personal',
		active: true,
		sortOrder: 80,
	},
	{
		id: 'unpaid-leave',
		name: 'Ausencia no retribuida',
		description: 'Ausencia no retribuida solicitada por la persona trabajadora.',
		category: 'unpaid_leave',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: true,
		documentRequirement: 'none',
		allowsPastRequests: false,
		minimumNoticeDays: null,
		calendarToken: 'unpaid',
		active: true,
		sortOrder: 90,
	},
	{
		id: 'medical-leave',
		name: 'Baja médica',
		description: 'Ausencia por baja médica.',
		category: 'medical_leave',
		unit: 'days',
		defaultDuration: null,
		deductsVacationBalance: false,
		reducesExpectedHours: true,
		requiresApproval: false,
		documentRequirement: 'required',
		allowsPastRequests: true,
		minimumNoticeDays: null,
		calendarToken: 'sick-leave',
		active: true,
		sortOrder: 100,
	},
];
